repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest tests --cov=cosmotech.data_update_quest --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
